import { MaintenanceRecord } from '../types';

export const INITIAL_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  // EDM-W01: Makino U6 H.E.A.T
  {
    id: 'maint-01',
    deviceId: 'dev-01',
    taskTitle: 'Bảo dưỡng định kỳ 500 giờ & Thay cụm dẫn hướng kim cương P-104',
    taskType: 'PREVENTIVE',
    completedAt: '2026-09-22T14:30:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 95,
    partsReplaced: [
      'Bộ dẫn hướng kim cương trên/dưới 0.25mm (Diamond Wire Guide)',
      'Khối tiếp điện cacbua (Energizing Carbide Plate)',
      'Lõi lọc giấy ion 3-micron',
    ],
    findingsAndActions:
      'Cụm dẫn hướng kim cương trên có vết xước do xỉ mạ. Đã tháo rỡ, ngâm rửa siêu âm và thay mới bộ dẫn hướng kim cương 0.25mm. Căn chỉnh góc nghiêng U/V bằng thước chuẩn quang học.',
    technicianNotes: 'Độ chính xác cắt thẳng sau bảo dưỡng đạt 0.0015mm trên phôi mẫu thép SKD11.',
    operatingHoursAtMaintenance: 4210,
    qualityPassed: true,
    costEstimateVND: 6800000,
    aiVerified: true,
  },
  {
    id: 'maint-02',
    deviceId: 'dev-01',
    taskTitle: 'Khắc phục khẩn cấp đứt dây cắt & Súc rửa vòi phun áp lực cao (E-102)',
    taskType: 'CORRECTIVE',
    completedAt: '2026-09-12T09:15:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 45,
    partsReplaced: [
      'Ống xả áp cao Upper Nozzle 4mm',
      'Gioăng cao su làm kín nắp buồng phun',
    ],
    findingsAndActions:
      'Vòi phun áp suất cao phía trên bị nghẹt 35% tiết diện do phoi sắt vụn. Áp suất xả chỉ đạt 0.7 MPa. Đã thông tắc bằng siêu âm, thay vòi mới và cân bằng áp lực đạt 1.8 MPa.',
    technicianNotes: 'Sau khắc phục, máy chạy liên tục 48 giờ không còn phát sinh đứt dây tại khe phóng điện.',
    operatingHoursAtMaintenance: 4140,
    qualityPassed: true,
    costEstimateVND: 2200000,
    aiVerified: true,
  },
  {
    id: 'maint-03',
    deviceId: 'dev-01',
    taskTitle: 'Hiệu chuẩn cảm biến áp lực dầu & Bơm mỡ thanh trượt trục X/Y',
    taskType: 'CALIBRATION',
    completedAt: '2026-08-28T16:00:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 60,
    partsReplaced: ['Mỡ bôi trơn chuyên dụng Kluber Isoflex NBU 15 (Tuýp 400g)'],
    findingsAndActions:
      'Bơm mỡ tự động cho 4 cụm block trượt THK trục X và Y. Đo kiểm độ rơ trục vít me bi (backlash): Trục X đạt 0.002mm, Trục Y đạt 0.002mm.',
    technicianNotes: 'Độ êm ái vận hành tốt, không phát sinh nhiệt dư thừa khi chạy chế độ Rapid 3000mm/phút.',
    operatingHoursAtMaintenance: 4020,
    qualityPassed: true,
    costEstimateVND: 1500000,
    aiVerified: false,
  },

  // EDM-W02: Sodick ALC600G
  {
    id: 'maint-04',
    deviceId: 'dev-02',
    taskTitle: 'Bảo dưỡng bơm dung môi áp lực & Thay thế phớt trục cơ khí Ceramic',
    taskType: 'PREVENTIVE',
    completedAt: '2026-09-18T11:20:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 110,
    partsReplaced: [
      'Phớt cơ khí làm kín Ceramic Mechanical Seal 22mm',
      'Bộ lọc than hoạt tính hấp phụ hạt ion',
      'Dây curoa truyền động bơm Grundfos',
    ],
    findingsAndActions:
      'Phớt bơm cũ có dấu hiệu rỉ dầu nhẹ ra khay hứng. Đã tháo rỡ toàn bộ cụm buồng bơm, thay phớt gốm mới và cân chỉnh đồng trục động cơ.',
    technicianNotes: 'Áp lực bơm sau thay thế đạt 1.65 Bar ổn định, không còn bọt khí xâm thực.',
    operatingHoursAtMaintenance: 3580,
    qualityPassed: true,
    costEstimateVND: 4900000,
    aiVerified: true,
  },
  {
    id: 'maint-05',
    deviceId: 'dev-02',
    taskTitle: 'Vệ sinh tản nhiệt khối công suất IGBT & Thay quạt hút tủ điều khiển (SPW-303)',
    taskType: 'CORRECTIVE',
    completedAt: '2026-09-05T15:45:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 40,
    partsReplaced: [
      'Quạt tản nhiệt biến tần Sunon MagLev 24VDC 120mm',
      'Tấm mút lọc bụi tĩnh điện cửa tủ điều khiển',
    ],
    findingsAndActions:
      'Quạt tản nhiệt khối IGBT bị kẹt do bụi than xưởng cơ khí, gây tăng nhiệt lên 68°C. Đã thay quạt mới và làm sạch lá nhôm tản nhiệt bằng khí khô.',
    technicianNotes: 'Nhiệt độ IGBT hạ xuống 39°C trong điều kiện cắt thô 32A liên tục.',
    operatingHoursAtMaintenance: 3490,
    qualityPassed: true,
    costEstimateVND: 1800000,
    aiVerified: true,
  },

  // EDM-S01: GF AgieCharmilles FORM E 350
  {
    id: 'maint-06',
    deviceId: 'dev-03',
    taskTitle: 'Hiệu chuẩn độ phẳng bàn làm việc & Kiểm tra cụm xả xung điện cực Z',
    taskType: 'CALIBRATION',
    completedAt: '2026-09-25T10:00:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 75,
    partsReplaced: [
      'Bộ gioăng Viton O-ring chịu dầu chịu nhiệt van xả',
      'Bộ lọc xả áp nhanh FESTO 1/4 inch',
    ],
    findingsAndActions:
      'Sử dụng đồng hồ so Mitutoyo 0.001mm rà độ phẳng bàn gá từ tính Erowa. Độ nghiêng hiệu chỉnh về 0.002mm/200mm. Kiểm tra tốc độ phản hồi servo Z.',
    technicianNotes: 'Đáp ứng gia công khuôn mẫu điện cực than chì độ bóng gương VDI 12.',
    operatingHoursAtMaintenance: 2890,
    qualityPassed: true,
    costEstimateVND: 2500000,
    aiVerified: true,
  },
  {
    id: 'maint-07',
    deviceId: 'dev-03',
    taskTitle: 'Thay dầu điện môi dielektrikum & Súc rửa bể lắng cặn xỉ',
    taskType: 'PARTS_REPLACEMENT',
    completedAt: '2026-08-15T13:30:00Z',
    technicianName: 'Phạm Quốc Tuấn',
    technicianRole: 'Kỹ sư Ứng dụng EDM',
    durationMinutes: 140,
    partsReplaced: [
      '120 Lít dầu xung điện Oest Dielektrikum 200',
      'Cặp phin lọc xỉ ly tâm 5-micron',
    ],
    findingsAndActions:
      'Hút toàn bộ 120 lít dầu cũ biến chất có độ nhớt tăng. Làm sạch cặn đáy bể bằng máy hút công nghiệp. Bơm dầu mới và chạy tuần hoàn lọc 3 giờ.',
    technicianNotes: 'Màu dầu trong suốt, độ cách điện đạt chuẩn phóng tia lửa ổn định.',
    operatingHoursAtMaintenance: 2780,
    qualityPassed: true,
    costEstimateVND: 8500000,
    aiVerified: true,
  },

  // EDM-W03: Fanuc Robocut α-C600iB
  {
    id: 'maint-08',
    deviceId: 'dev-04',
    taskTitle: 'Kiểm tra hệ thống luồn dây tự động AWF & Căn chỉnh mỏ nhiệt cắt dây',
    taskType: 'PREVENTIVE',
    completedAt: '2026-09-20T08:30:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 50,
    partsReplaced: [
      'Điện trở nhiệt mỏ cắt dây AWF Annealing Unit',
      'Bánh lăn kéo dây dẫn phế liệu (Discharge Roller)',
    ],
    findingsAndActions:
      'Đầu mỏ nhiệt cắt dây bị đóng muội xỉ khiến đầu dây đồng bị tòe khi cắt. Đã làm sạch đầu điện cực nhiệt và thay bánh lăn kéo dây bọc cao su PU.',
    technicianNotes: 'Thử nghiệm luồn dây qua lỗ mồi ø0.5mm thành công 10/10 lần liên tục.',
    operatingHoursAtMaintenance: 3120,
    qualityPassed: true,
    costEstimateVND: 3100000,
    aiVerified: true,
  },

  // CNC-M01: DMG Mori CMX 600V
  {
    id: 'maint-09',
    deviceId: 'dev-05',
    taskTitle: 'Bảo dưỡng trục chính 12,000 RPM & Kiểm tra lực kẹp dao thủy lực',
    taskType: 'PREVENTIVE',
    completedAt: '2026-09-14T14:00:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 120,
    partsReplaced: [
      'Bộ đĩa lò xo kẹp dao OTT-Jakob BBT40',
      'Lọc dầu hồi hệ thống thủy lực 10-micron',
    ],
    findingsAndActions:
      'Đo lực kéo rút dao thủy lực đạt 11.2 kN (đạt tiêu chuẩn yêu cầu >10.5 kN). Độ đảo côn trục chính ở đầu gá dao kiểm tra đạt 0.0018mm.',
    technicianNotes: 'Trục chính chạy êm không rung, độ ồn 68dB ở vòng tua tối đa 12,000 vòng/phút.',
    operatingHoursAtMaintenance: 5400,
    qualityPassed: true,
    costEstimateVND: 7200000,
    aiVerified: true,
  },

  // EDM-D01: Castek CNC ZNC-400
  {
    id: 'maint-10',
    deviceId: 'dev-06',
    taskTitle: 'Bảo dưỡng động cơ servo trục Z & Kiểm tra van xả nước áp lực cao',
    taskType: 'PREVENTIVE',
    completedAt: '2026-09-10T10:15:00Z',
    technicianName: 'Phạm Quốc Tuấn',
    technicianRole: 'Kỹ sư Ứng dụng EDM',
    durationMinutes: 65,
    partsReplaced: [
      'Bộ gioăng cao su van xả đáy bể',
      '5 Cây ống đồng dẫn điện cực ø1.0mm',
    ],
    findingsAndActions:
      'Bảo dưỡng vệ sinh rãnh trượt servo nâng hạ đầu điện cực đục lỗ. Thay van xả đáy để giải quyết tình trạng rò rỉ dung môi.',
    technicianNotes: 'Khoan lỗ mồi xỏ dây tốc độ 35mm/phút trên thép tôi SKD11 đạt yêu cầu.',
    operatingHoursAtMaintenance: 2150,
    qualityPassed: true,
    costEstimateVND: 1900000,
    aiVerified: false,
  },

  // Additional 6-Month Historical Maintenance Records for Frequency Trend Analysis
  // EDM-W01: Makino U6 H.E.A.T
  {
    id: 'maint-01-aug',
    deviceId: 'dev-01',
    taskTitle: 'Thay lõi lọc ion & Hiệu chuẩn lực căng dây cắt 12N',
    taskType: 'PREVENTIVE',
    completedAt: '2026-08-10T09:30:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 80,
    partsReplaced: ['Lõi lọc giấy ion 3-micron', 'Lò xo cảm biến lực căng dây'],
    findingsAndActions: 'Lực căng dây cắt sụt giảm 1.5N do lò xo hồi vị mỏi. Đã thay lò xo và cân chuẩn lực căng 12N.',
    technicianNotes: 'Dây chạy êm ái, độ ổn định phóng tia lửa đạt mức cao nhất.',
    operatingHoursAtMaintenance: 3950,
    qualityPassed: true,
    costEstimateVND: 3500000,
    aiVerified: true,
  },
  {
    id: 'maint-01-jul2',
    deviceId: 'dev-01',
    taskTitle: 'Thay con lăn dẫn hướng cấp dây tự động AWF',
    taskType: 'PARTS_REPLACEMENT',
    completedAt: '2026-07-25T15:00:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 60,
    partsReplaced: ['Con lăn dẫn hướng Polyurethane AWF-R10'],
    findingsAndActions: 'Con lăn cấp dây bị mòn rãnh sâu 0.3mm gây trượt dây mồi. Đã thay mới và bôi mỡ chuyên dụng.',
    technicianNotes: 'Tỷ lệ luồn dây tự động phục hồi đạt 100%.',
    operatingHoursAtMaintenance: 3880,
    qualityPassed: true,
    costEstimateVND: 2400000,
    aiVerified: true,
  },
  {
    id: 'maint-01-jul1',
    deviceId: 'dev-01',
    taskTitle: 'Bảo dưỡng tổng thể chu kỳ 3500 giờ & Tẩy cặn buồng máy',
    taskType: 'PREVENTIVE',
    completedAt: '2026-07-04T13:00:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 120,
    partsReplaced: ['Bộ lọc khí nén SMC', 'Gioăng đệm nắp bàn thao tác'],
    findingsAndActions: 'Thực hiện vệ sinh sâu khoang cắt, tẩy xỉ bám bằng hóa chất trung tính và bôi trơn hệ thống cơ khí.',
    technicianNotes: 'Toàn bộ thông số thủy lực và điện môi đạt tiêu chuẩn OEM.',
    operatingHoursAtMaintenance: 3810,
    qualityPassed: true,
    costEstimateVND: 5100000,
    aiVerified: true,
  },
  {
    id: 'maint-01-jun',
    deviceId: 'dev-01',
    taskTitle: 'Hiệu chuẩn quang học góc nghiêng tháp cắt U-V và Z',
    taskType: 'CALIBRATION',
    completedAt: '2026-06-18T10:30:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 90,
    partsReplaced: ['Khối chuẩn vuông góc góc thau EDM'],
    findingsAndActions: 'Rà kiểm góc nghiêng tháp U/V cắt côn góc 15 độ. Hiệu chỉnh bù trừ sai số bù góc về 0.002 độ.',
    technicianNotes: 'Kiểm tra cắt thử mẫu côn đạt tiêu chuẩn khuôn ép chính xác.',
    operatingHoursAtMaintenance: 3670,
    qualityPassed: true,
    costEstimateVND: 2900000,
    aiVerified: true,
  },
  {
    id: 'maint-01-may',
    deviceId: 'dev-01',
    taskTitle: 'Thay cụm tiếp điện Carbide & Kiểm tra áp lực xả dung môi',
    taskType: 'PREVENTIVE',
    completedAt: '2026-05-22T14:15:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 70,
    partsReplaced: ['Khối tiếp điện cacbua (Energizing Carbide Plate)'],
    findingsAndActions: 'Đảo mặt khối tiếp điện và thay mới khối trên. Kiểm tra áp lực xả vòi đạt 1.85 MPa.',
    technicianNotes: 'Nghiệm thu phóng tia lửa ổn định.',
    operatingHoursAtMaintenance: 3510,
    qualityPassed: true,
    costEstimateVND: 2800000,
    aiVerified: true,
  },

  // EDM-W02: Sodick ALC600G
  {
    id: 'maint-02-aug',
    deviceId: 'dev-02',
    taskTitle: 'Hiệu chuẩn động cơ tuyến tính Linear Motor trục X/Y',
    taskType: 'CALIBRATION',
    completedAt: '2026-08-20T11:00:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 85,
    partsReplaced: ['Cảm biến khe từ động cơ tuyến tính Sodick'],
    findingsAndActions: 'Đo kiểm độ hở khe từ động cơ tuyến tính trục X và Y. Cân chỉnh gia tốc servo mượt mà.',
    technicianNotes: 'Không phát sinh rung giật khi nội suy đường cong R nhỏ.',
    operatingHoursAtMaintenance: 3410,
    qualityPassed: true,
    costEstimateVND: 4200000,
    aiVerified: true,
  },
  {
    id: 'maint-02-jul',
    deviceId: 'dev-02',
    taskTitle: 'Thay hạt nhựa trao đổi ion Deionizing Resin & Bộ lọc 1-micron',
    taskType: 'PREVENTIVE',
    completedAt: '2026-07-30T14:40:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 75,
    partsReplaced: ['Bình hạt nhựa ion mixed-bed 50L', 'Cặp lõi lọc vi sợi 1-micron'],
    findingsAndActions: 'Điện trở suất nước điện môi giảm xuống dưới 40 kΩ.cm. Thay hạt nhựa mới đưa điện trở suất lên 120 kΩ.cm.',
    technicianNotes: 'Chất lượng bề mặt cắt đạt độ bóng Ra 0.28µm.',
    operatingHoursAtMaintenance: 3320,
    qualityPassed: true,
    costEstimateVND: 6300000,
    aiVerified: true,
  },
  {
    id: 'maint-02-jun',
    deviceId: 'dev-02',
    taskTitle: 'Thay phớt làm kín buồng gia công & Kiểm tra van khí nén',
    taskType: 'PARTS_REPLACEMENT',
    completedAt: '2026-06-25T09:30:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 60,
    partsReplaced: ['Gioăng chữ U phớt mép cửa buồng máy'],
    findingsAndActions: 'Phớt mép cửa lão hóa gây rỉ nước nhẹ. Đã làm sạch rãnh và thay thế phớt đệm chịu nước ion.',
    technicianNotes: 'Thử nghiệm bơm ngập buồng gia công đạt kín tuyệt đối.',
    operatingHoursAtMaintenance: 3200,
    qualityPassed: true,
    costEstimateVND: 1800000,
    aiVerified: true,
  },
  {
    id: 'maint-02-may',
    deviceId: 'dev-02',
    taskTitle: 'Bảo dưỡng định kỳ hệ thống giải nhiệt dầu và quạt tủ điện',
    taskType: 'PREVENTIVE',
    completedAt: '2026-05-14T15:30:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 70,
    partsReplaced: ['Tấm lọc bụi tủ biến tần', 'Dung dịch chống đóng cặn chiller'],
    findingsAndActions: 'Vệ sinh dàn tản nhiệt máy làm lạnh nước (chiller), kiểm tra áp suất gas R410A.',
    technicianNotes: 'Duy trì nhiệt độ nước điện môi 20°C ± 0.5°C ổn định.',
    operatingHoursAtMaintenance: 3080,
    qualityPassed: true,
    costEstimateVND: 2600000,
    aiVerified: true,
  },

  // EDM-S01: GF AgieCharmilles FORM E 350
  {
    id: 'maint-03-jul',
    deviceId: 'dev-03',
    taskTitle: 'Vệ sinh buồng xung dầu & Cân chỉnh mâm cặp điện cực Erowa',
    taskType: 'PREVENTIVE',
    completedAt: '2026-07-28T10:00:00Z',
    technicianName: 'Phạm Quốc Tuấn',
    technicianRole: 'Kỹ sư Ứng dụng EDM',
    durationMinutes: 90,
    partsReplaced: ['Bộ bi định vị mâm cặp Erowa ITS 50'],
    findingsAndActions: 'Làm sạch mâm kẹp điện cực, kiểm tra lực kẹp khí nén và độ lặp lại vị trí đạt 0.002mm.',
    technicianNotes: 'Đảm bảo độ chính xác gá đặt điện cực than chì.',
    operatingHoursAtMaintenance: 2690,
    qualityPassed: true,
    costEstimateVND: 3400000,
    aiVerified: true,
  },
  {
    id: 'maint-03-jun',
    deviceId: 'dev-03',
    taskTitle: 'Khắc phục sự cố kẹt van đảo chiều thủy lực bơm dầu xung',
    taskType: 'CORRECTIVE',
    completedAt: '2026-06-12T16:20:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 50,
    partsReplaced: ['Van điện từ tỷ lệ Rexroth 24VDC'],
    findingsAndActions: 'Van điện từ bị kẹt do cặn cacbon. Đã súc rửa đường ống và thay van điện từ mới.',
    technicianNotes: 'Tốc độ nâng hạ đầu điện cực phản hồi nhanh, không giật cục.',
    operatingHoursAtMaintenance: 2580,
    qualityPassed: true,
    costEstimateVND: 4600000,
    aiVerified: true,
  },
  {
    id: 'maint-03-may',
    deviceId: 'dev-03',
    taskTitle: 'Thay lõi lọc tinh & Bảo trì bơm tuần hoàn dung dịch',
    taskType: 'PREVENTIVE',
    completedAt: '2026-05-19T13:45:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 80,
    partsReplaced: ['Cặp phin lọc giấy xếp nếp 3-micron'],
    findingsAndActions: 'Thay phin lọc mới, xả khí trong đường ống dẫn và kiểm tra cảm biến áp suất chênh lệch.',
    technicianNotes: 'Hệ thống vận hành trơn tru.',
    operatingHoursAtMaintenance: 2460,
    qualityPassed: true,
    costEstimateVND: 2900000,
    aiVerified: true,
  },

  // EDM-W03: Fanuc Robocut α-C600iB
  {
    id: 'maint-04-aug',
    deviceId: 'dev-04',
    taskTitle: 'Thay bộ tiếp điện xung & Bạc đạn con lăn thu gom dây',
    taskType: 'PARTS_REPLACEMENT',
    completedAt: '2026-08-25T14:10:00Z',
    technicianName: 'Lê Hoàng Nam',
    technicianRole: 'Chuyên gia Cắt Dây EDM',
    durationMinutes: 65,
    partsReplaced: ['Khối tiếp điện thau Fanuc chính hãng', 'Vòng bi NSK 6000ZZ con lăn xả dây'],
    findingsAndActions: 'Thay bạc đạn con lăn thu dây phế liệu để loại bỏ tiếng rít. Thay khối tiếp điện thau.',
    technicianNotes: 'Hệ thống kéo dây hoạt động êm ái dưới 60dB.',
    operatingHoursAtMaintenance: 3010,
    qualityPassed: true,
    costEstimateVND: 3800000,
    aiVerified: true,
  },
  {
    id: 'maint-04-jul',
    deviceId: 'dev-04',
    taskTitle: 'Cân chỉnh tọa độ gốc phôi & Góc nghiêng tháp cắt U-V',
    taskType: 'CALIBRATION',
    completedAt: '2026-07-15T09:30:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 70,
    partsReplaced: ['Đầu dò kim loại tự động Fanuc Touch Sensor'],
    findingsAndActions: 'Căn chỉnh cảm biến chạm vi điểm để dò cạnh phôi tự động. Độ lặp lại đạt 0.001mm.',
    technicianNotes: 'Đáp ứng gia công khuôn linh kiện điện tử siêu chính xác.',
    operatingHoursAtMaintenance: 2900,
    qualityPassed: true,
    costEstimateVND: 2700000,
    aiVerified: true,
  },
  {
    id: 'maint-04-jun',
    deviceId: 'dev-04',
    taskTitle: 'Thay nhựa khử ion & Bộ màng lọc giấy kép',
    taskType: 'PREVENTIVE',
    completedAt: '2026-06-08T15:20:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 60,
    partsReplaced: ['Thùng hạt nhựa ion Purolite 40L', 'Lõi lọc giấy kép Fanuc'],
    findingsAndActions: 'Thay thế hạt nhựa khử ion và bộ lọc định kỳ theo khuyến cáo nhà sản xuất Fanuc.',
    technicianNotes: 'Điện trở suất nước đạt 100 kΩ.cm.',
    operatingHoursAtMaintenance: 2790,
    qualityPassed: true,
    costEstimateVND: 5200000,
    aiVerified: true,
  },

  // CNC-M01: DMG Mori CMX 600V
  {
    id: 'maint-05-aug',
    deviceId: 'dev-05',
    taskTitle: 'Cân tâm trục chính và rà độ phẳng bàn máy',
    taskType: 'CALIBRATION',
    completedAt: '2026-08-18T11:30:00Z',
    technicianName: 'Trần Minh Đức',
    technicianRole: 'Kỹ thuật viên Cơ điện',
    durationMinutes: 90,
    partsReplaced: ['Thanh cữ hiệu chuẩn Renishaw'],
    findingsAndActions: 'Kiểm tra độ võng và độ nghiêng trục chính. Hiệu chỉnh bù trừ góc nghiêng trục Z.',
    technicianNotes: 'Độ chính xác định vị trục Z đạt 0.003mm trên toàn hành trình.',
    operatingHoursAtMaintenance: 5280,
    qualityPassed: true,
    costEstimateVND: 3500000,
    aiVerified: true,
  },
  {
    id: 'maint-05-jul',
    deviceId: 'dev-05',
    taskTitle: 'Bơm mỡ bôi trơn trục vít me và vệ sinh thùng làm mát',
    taskType: 'PREVENTIVE',
    completedAt: '2026-07-20T13:40:00Z',
    technicianName: 'Phạm Quốc Tuấn',
    technicianRole: 'Kỹ sư Ứng dụng EDM',
    durationMinutes: 100,
    partsReplaced: ['Mỡ bôi trơn LHL-X100', 'Lưới chắn phoi thùng nước tưới nguội'],
    findingsAndActions: 'Thực hiện xả cặn thùng nước làm mát, bổ sung dầu tưới nguội pha nước nồng độ 8%.',
    technicianNotes: 'Nồng độ brix đạt chuẩn chống gỉ phôi mẫu.',
    operatingHoursAtMaintenance: 5120,
    qualityPassed: true,
    costEstimateVND: 2800000,
    aiVerified: true,
  },

  // EDM-D01: Castek CNC ZNC-400
  {
    id: 'maint-06-aug',
    deviceId: 'dev-06',
    taskTitle: 'Thay ống đồng dẫn hướng điện cực đục lỗ và bộ phớt áp',
    taskType: 'PARTS_REPLACEMENT',
    completedAt: '2026-08-14T10:50:00Z',
    technicianName: 'Phạm Quốc Tuấn',
    technicianRole: 'Kỹ sư Ứng dụng EDM',
    durationMinutes: 55,
    partsReplaced: ['Cụm ống dẫn hướng Ceramic Guide ø0.8mm', 'Gioăng đệm áp lực cao'],
    findingsAndActions: 'Thay ống gốm dẫn hướng chống mòn cho trục đục lỗ mồi EDM.',
    technicianNotes: 'Lỗ khoan thẳng đều không lệch tâm.',
    operatingHoursAtMaintenance: 2050,
    qualityPassed: true,
    costEstimateVND: 1700000,
    aiVerified: true,
  },
  {
    id: 'maint-06-jul',
    deviceId: 'dev-06',
    taskTitle: 'Bảo trì bơm cao áp xả xỉ mồi xỏ dây & Vệ sinh van đảo',
    taskType: 'PREVENTIVE',
    completedAt: '2026-07-19T14:20:00Z',
    technicianName: 'Nguyễn Văn Hùng',
    technicianRole: 'Kỹ sư Trưởng Bảo Trì',
    durationMinutes: 70,
    partsReplaced: ['Piston bơm cao áp inox 316', 'Van tiết lưu cao áp'],
    findingsAndActions: 'Súc rửa cụm bơm áp 70 bar, thay thế van tiết lưu bảo vệ quá áp.',
    technicianNotes: 'Tia nước thoát xỉ mạnh, tốc độ khoan lỗ tăng 20%.',
    operatingHoursAtMaintenance: 1940,
    qualityPassed: true,
    costEstimateVND: 3200000,
    aiVerified: true,
  },
];

const STORAGE_KEY = 'edm_smartguard_maintenance_records_v2';

export function getStoredMaintenanceRecords(): MaintenanceRecord[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_MAINTENANCE_RECORDS));
      return INITIAL_MAINTENANCE_RECORDS;
    }
    return JSON.parse(raw);
  } catch {
    return INITIAL_MAINTENANCE_RECORDS;
  }
}

export function saveMaintenanceRecord(record: MaintenanceRecord): MaintenanceRecord[] {
  try {
    const current = getStoredMaintenanceRecords();
    const updated = [record, ...current];
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    return updated;
  } catch (err) {
    console.error('Failed to save maintenance record:', err);
    return INITIAL_MAINTENANCE_RECORDS;
  }
}

export function getDeviceMaintenanceHistory(deviceId: string): MaintenanceRecord[] {
  const all = getStoredMaintenanceRecords();
  return all.filter((r) => r.deviceId === deviceId);
}
